name: ðŸŒ¸ ç¼–è¯‘å‘å¸ƒæµ‹è¯•çŽ¯å¢ƒ
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20.0.0

      - name: Setup Nodejs
        run: |
          echo "::remove-matcher owner=eslint-compact::"
          echo "::remove-matcher owner=eslint-stylish::"
          echo "NOW=$(date -u)" >> $GITHUB_ENV

      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          CI=false PUBLIC_URL=${{ secrets.DEV_PUBLIC_URL }} \
          REACT_APP_API_URL=${{ secrets.DEV_REACT_APP_API_URL }} \
          REACT_APP_STORE_KEY=${{ secrets.DEV_REACT_APP_STORE_KEY }} \
          REACT_APP_BUILD_ID=${GITHUB_SHA} \
          REACT_APP_BUILD_BRANCH=${GITHUB_REF_NAME} \
          REACT_APP_BUILD_TIME="${{ env.NOW }}" \
          npm run build

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-dev
          folder: build # The folder the action should deploy.